<?php

return [
//   A  B  C  D  E  F  G
    [INFINITE, 1, 2, INFINITE, INFINITE, INFINITE, INFINITE], // A
    [1, INFINITE, INFINITE, 2, INFINITE,3, INFINITE], // B
    [2, INFINITE, INFINITE, 3, 4,INFINITE], // C
    [INFINITE, 2, 3, INFINITE, 2,3,3], // D
    [INFINITE, INFINITE, 4, 2, INFINITE,INFINITE,5], //E
    [INFINITE, 3, INFINITE, 3, INFINITE,INFINITE,4], // F
    [INFINITE, INFINITE, INFINITE, 3, 5,4,INFINITE], // G

];